import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ObserverProvider from "@/ObserverProvider";

const poppins = localFont({
  src: [
    { path: "/fonts/Poppins-Italic.ttf", weight: "400", style: "normal" },
    { path: "/fonts/Poppins-Medium.ttf", weight: "500", style: "normal" },
    { path: "/fonts/Poppins-Regular.ttf", weight: "400", style: "normal" },
    { path: "/fonts/Poppins-SemiBold.ttf", weight: "600", style: "normal" },
  ],
  variable: "--poppins",
});

export const metadata: Metadata = {
  title: "Mylaru Infra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poppins.variable} antialiased`}>
        <ObserverProvider>{children}</ObserverProvider>
      </body>
    </html>
  );
}
